name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - 'lint.rb'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: |
          swiftlint | sed -E "s/$(pwd|sed 's/\//\\\//g')\///" | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'

